project = simulinkproject;
desiredPathFromProjectRoot = ...
    [project.RootFolder '/untracked_nibp_processor'];

myCacheFolder = fullfile(desiredPathFromProjectRoot, 'simCache');
myCodeGenFolder = fullfile(desiredPathFromProjectRoot, 'codeGen');

Simulink.fileGenControl('set',...
    'CacheFolder', myCacheFolder,...
    'CodeGenFolder', myCodeGenFolder,...
    'createDir', true);